package model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 07 14:35:49 CEST 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LOVLocationViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LOVLocationViewImpl() {
    }
}

